#index:
#    path: /
#    controller: App\Controller\DefaultController::index

salle_tp_accueil:
  path: /accueil
  controller: App\Controller\SalleController::accueil

salle_tp_afficher:
  path:  /afficher/{numero}
  controller: App\Controller\SalleController::afficher

salle_tp_dix:
  path: /dix
  controller: App\Controller\SalleController::dix

salle_tp_test_xml:
  path: /test/xml
  controller: App\Controller\SalleController::testXml

salle_tp_test_json:
  path: /test/json
  controller: App\Controller\SalleController::testJson

salle_tp_treize:
  path: /treize
  controller: App\Controller\SalleController::treize

salle_tp_quatorze:
  path: /quatorze
  controller: App\Controller\SalleController::quatorze

salle_tp_voir:
  path: /voir/{id}
  controller: App\Controller\SalleController::voir
  requirements:
    numero: \d+

salle_tp_ajouter:
  path: /ajouter/{batiment}-{etage}.{numero}
  controller: App\Controller\SalleController::ajouter
  requirements:
    batiment: "A|B|C|D"
    etage: \d
    numero: \d{1,2}